# Generated by Django 3.2.6 on 2021-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='checkbox',
            field=models.CharField(default='', max_length=70),
        ),
    ]
